// "use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
// import { useState } from "react";
// import CookiePolicy from "@/components/CookiePolicy";
import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// const [cookiePolicy, setCookiePolicy] = useState<boolean>(false);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
        <html lang="en" className="h-full">
          <body
            className={cn(
              "relative h-full font-sans antialiased",
              inter.className
            )}
          >
            <main className="relative flex flex-col min-h-screen">
              {/* <Providers> */}
              <Navbar />
              <div className="flex-grow flex-1">{children}</div>
              <Footer />
              {/* </Providers> */}
            </main>
            {/* <CookiePolicy
          show={cookiePolicy}
          // onClose={() => setCookiePolicy(false)}
        /> */}
            <Toaster position="top-center" richColors />
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
