// "use client";
import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
// import { useState } from "react";
// import CookiePolicy from "@/components/CookiePolicy";
import { ClerkProvider } from "@clerk/nextjs";
import { StoreProvider } from "@/context/StoreContext";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const [cookiePolicy, setCookiePolicy] = useState<boolean>(false);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <StoreProvider>
        <html lang="en" className="h-full antialiased">
          <body
            className={cn(
              "relative h-full font-sans antialiased",
              inter.className
            )}
          >
            <Navbar />
            <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
              <div className="flex-1 flex flex-col h-full">{children}</div>
              <Footer />
            </main>
            <GoogleTagManager gtmId="GTM-PMNBH7QM" />
            <Toaster position="top-center" richColors />
          </body>
          <GoogleAnalytics gaId="G-R5GNET16RC" />
        </html>
      </StoreProvider>
    </ClerkProvider>
  );
}
